imports:
    - { resource: config.yml }


# Framework Configuration
framework:
    profiler: { only_exceptions: false }


# WebProfiler Configuration
web_profiler:
    toolbar: true
    intercept_redirects: false


# Monolog Configuration
monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        console:
            type: console
            channels: ['!event', '!doctrine']

